In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("C:\\Users\\HP\\Desktop\\Python\\AI\\DataSet\\earthquakes.csv")
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,id,updated,place,type
0,2014-01-31 23:53:37.000,60.252000,-152.7081,90.20,1.10,ml,NaN,NaN,NaN,0.2900,ak,ak11155107,2014-02-05T19:34:41.515Z,"26km S of Redoubt Volcano, Alaska",earthquake
1,2014-01-31 23:48:35.452,37.070300,-115.1309,0.00,1.33,ml,4.0,171.43,0.34200,0.0247,nn,nn00436847,2014-02-01T01:35:09.000Z,"32km S of Alamo, Nevada",earthquake
2,2014-01-31 23:47:24.000,64.671700,-149.2528,7.10,1.30,ml,NaN,NaN,NaN,1.0000,ak,ak11151142,2014-02-01T00:03:53.010Z,"12km NNW of North Nenana, Alaska",earthquake
3,2014-01-31 23:30:54.000,63.188700,-148.9575,96.50,0.80,ml,NaN,NaN,NaN,1.0700,ak,ak11151135,2014-01-31T23:41:25.007Z,"22km S of Cantwell, Alaska",earthquake
4,2014-01-31 23:30:52.210,32.616833,-115.6925,10.59,1.34,ml,6.0,285.00,0.04321,0.2000,ci,ci37171541,2014-02-01T00:13:20.107Z,"10km WNW of Progreso, Mexico",earthquake

In [4]:
df.rename(columns={'time':'dates'})
df.set_index('id')

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,updated,place,type
id,,,,,,,,,,,,,,
ak11155107,2014-01-31 23:53:37.000,60.252000,-152.708100,90.200,1.10,ml,NaN,NaN,NaN,0.2900,ak,2014-02-05T19:34:41.515Z,"26km S of Redoubt Volcano, Alaska",earthquake
nn00436847,2014-01-31 23:48:35.452,37.070300,-115.130900,0.000,1.33,ml,4.0,171.430000,0.342000,0.0247,nn,2014-02-01T01:35:09.000Z,"32km S of Alamo, Nevada",earthquake
ak11151142,2014-01-31 23:47:24.000,64.671700,-149.252800,7.100,1.30,ml,NaN,NaN,NaN,1.0000,ak,2014-02-01T00:03:53.010Z,"12km NNW of North Nenana, Alaska",earthquake
ak11151135,2014-01-31 23:30:54.000,63.188700,-148.957500,96.500,0.80,ml,NaN,NaN,NaN,1.0700,ak,2014-01-31T23:41:25.007Z,"22km S of Cantwell, Alaska",earthquake
ci37171541,2014-01-31 23:30:52.210,32.616833,-115.692500,10.590,1.34,ml,6.0,285.000000,0.043210,0.2000,ci,2014-02-01T00:13:20.107Z,"10km WNW of Progreso, Mexico",earthquake
ci11419722,2014-01-31 23:30:36.930,32.567667,-117.013500,0.010,1.51,ml,16.0,264.000000,0.080810,0.2100,ci,2014-02-01T00:09:04.470Z,"3km N of Tijuana, Mexico",quarry blast
ci11419714,2014-01-31 23:28:04.020,33.359000,-116.360500,12.980,1.17,ml,26.0,163.000000,0.032660,0.1200,ci,2014-02-01T00:54:07.630Z,"11km N of Borrego Springs, California",earthquake
ak11151127,2014-01-31 23:22:52.000,62.800200,-150.696500,86.400,1.50,ml,NaN,NaN,NaN,0.4700,ak,2014-01-31T23:33:23.190Z,"61km NNW of Talkeetna, Alaska",earthquake
ak11151125,2014-01-31 23:20:42.000,58.169500,-151.992400,50.100,2.10,ml,NaN,NaN,NaN,0.3700,ak,2014-01-31T23:25:57.118Z,"48km NNE of Kodiak, Alaska",earthquake
nc72153361,2014-01-31 23:17:34.300,37.686000,-121.728700,4.200,1.60,Md,NaN,111.600000,0.062882,0.0700,nc,2014-02-11T22:43:08.085Z,"3km E of Livermore, California",earthquake
usc000mqlp,2014-01-31 23:08:03.660,-4.975800,153.946600,110.180,4.20,mb,NaN,98.000000,1.940000,0.6100,us,2014-04-08T01:43:19.000Z,"115km ESE of Taron, Papua New Guinea",earthquake
ak11155101,2014-01-31 23:01:26.000,60.385200,-147.650500,13.100,1.10,ml,NaN,NaN,NaN,0.3500,ak,2014-02-05T04:05:14.896Z,"71km SE of Whittier, Alaska",earthquake
nc72153351,2014-01-31 22:56:11.900,38.781200,-122.755800,2.100,0.90,Md,NaN,79.200000,0.008983,0.0200,nc,2014-01-31T23:42:09.182Z,"0km N of The Geysers, California",earthquake
nc72153356,2014-01-31 22:55:55.900,37.634800,-119.019500,4.200,0.10,Md,NaN,86.400000,0.008983,0.0600,nc,2014-02-11T01:58:47.547Z,"4km WSW of Mammoth Lakes, California",earthquake
usc000mqln,2014-01-31 22:54:32.970,-28.177500,-177.905800,95.840,4.30,mb,NaN,104.000000,1.063000,1.1400,us,2014-04-08T01:43:19.000Z,"120km N of Raoul Island, New Zealand",earthquake
nm020414a,2014-01-31 22:54:06.200,36.538300,-89.629000,7.800,1.50,md,13.0,100.799992,0.035933,0.3400,nm,2014-02-04T14:10:26.871Z,"6km SSW of Lilbourn, Missouri",earthquake
usc000mqls,2014-01-31 22:49:49.740,-23.119200,179.117400,528.340,4.40,mb,NaN,80.000000,5.439000,0.9500,us,2014-04-08T01:43:19.000Z,South of the Fiji Islands,earthquake
ci11419698,2014-01-31 22:49:13.930,33.003000,-116.321167,10.490,1.78,ml,51.0,57.000000,0.104500,0.2100,ci,2014-02-01T00:06:58.130Z,"27km ESE of Julian, California",earthquake
ci11419706,2014-01-31 22:47:21.750,36.131667,-118.079167,5.610,1.18,ml,14.0,145.000000,0.182100,0.1800,ci,2014-01-31T23:47:24.935Z,"52km S of Lone Pine, California",earthquake
ak11151102,2014-01-31 22:45:19.000,64.995400,-147.331300,0.100,1.10,ml,NaN,NaN,NaN,0.7900,ak,2014-01-31T22:58:41.619Z,"23km NNE of Badger, Alaska",earthquake
nc72153341,2014-01-31 22:35:53.900,38.585800,-122.458300,6.700,1.20,Md,NaN,61.200000,0.062882,0.1100,nc,2014-02-11T02:26:09.007Z,"1km NNW of Angwin, California",earthquake
mb14328395,2014-01-31 22:31:14.800,46.820100,-112.199600,7.900,1.50,Md,20.0,183.600000,0.597380,0.1900,mb,2014-02-03T23:06:21.933Z,"14km NW of Helena Valley Northwest, Montana",earthquake
ci11419690,2014-01-31 22:30:54.000,35.987333,-117.414500,7.990,0.94,ml,10.0,161.000000,0.092840,0.1500,ci,2014-01-31T23:44:34.918Z,"24km N of Searles Valley, California",earthquake
nc72153331,2014-01-31 22:26:40.400,38.817500,-122.816000,3.000,0.50,Md,NaN,111.600000,0.008983,0.0200,nc,2014-01-31T23:18:06.391Z,"6km NW of The Geysers, California",earthquake
pr14031002,2014-01-31 22:22:14.600,18.482500,-64.760800,91.000,3.40,Md,4.0,342.000000,0.843518,0.0700,pr,2014-04-08T01:43:19.000Z,"16km WNW of Road Town, British Virgin Islands",earthquake
ak11151084,2014-01-31 22:20:19.000,61.742600,-152.009800,102.200,1.40,ml,NaN,NaN,NaN,0.3000,ak,2014-01-31T22:45:05.416Z,"104km W of Willow, Alaska",earthquake
usc000mf1x,2014-01-31 22:19:44.330,51.156900,-178.091000,37.500,4.20,mb,NaN,NaN,NaN,0.8300,us,2014-04-08T01:43:19.000Z,"72km E of Amatignak Island, Alaska",earthquake
ci11419682,2014-01-31 22:19:12.180,34.315500,-116.900833,9.150,0.96,ml,28.0,166.000000,0.055570,0.1400,ci,2014-01-31T23:38:32.200Z,"7km NW of Big Bear City, California",earthquake
ci11419674,2014-01-31 22:17:28.030,33.367000,-116.388167,13.020,1.02,ml,25.0,155.000000,0.043850,0.1700,ci,2014-01-31T23:23:18.900Z,"12km N of Borrego Springs, California",earthquake
ak11151076,2014-01-31 22:16:01.000,60.039800,-141.762900,4.200,1.20,ml,NaN,NaN,NaN,0.6000,ak,2014-01-31T22:39:08.447Z,"37km E of Cape Yakataga, Alaska",earthquake
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
usb000t1ww,2014-12-01 01:47:40.900,36.832400,-97.882300,3.858,2.50,ml,NaN,86.000000,NaN,0.5100,us,2015-02-24T00:35:14.040Z,"13km WNW of Medford, Oklahoma",earthquake
nc72358491,2014-12-01 01:44:24.770,38.823666,-122.843002,2.260,0.85,md,19.0,53.000000,0.006252,0.0300,nc,2014-12-01T02:19:01.958Z,"9km NW of The Geysers, California",earthquake
ci37065311,2014-12-01 01:43:46.510,33.969167,-116.914167,7.190,0.90,ml,41.0,53.000000,0.072930,0.1100,ci,2014-12-01T18:49:33.670Z,"6km NW of Banning, California",earthquake
nc72358486,2014-12-01 01:40:02.890,38.764667,-122.890667,3.940,1.17,md,34.0,121.000000,0.035560,0.0500,nc,2014-12-10T21:31:05.214Z,"11km ESE of Cloverdale, California",earthquake
hv60809571,2014-12-01 01:39:48.700,19.403300,-155.278500,1.400,2.10,Ml,NaN,39.600000,0.008983,0.1000,hv,2014-12-03T04:58:17.241Z,"5km SW of Volcano, Hawaii",earthquake
uw60926197,2014-12-01 01:30:33.300,43.715800,-121.237500,1.300,-0.40,Md,NaN,162.000000,0.008983,0.1200,uw,2014-12-01T03:57:01.107Z,"21km ESE of Three Rivers, Oregon",earthquake
nc72358481,2014-12-01 01:18:57.440,38.760167,-122.896000,4.110,0.79,md,25.0,75.000000,0.039950,0.0700,nc,2014-12-10T20:32:03.716Z,"11km ESE of Cloverdale, California",earthquake
mb14712763,2014-12-01 01:18:52.900,46.974300,-112.925800,14.800,1.00,mc,21.0,118.799990,0.102408,0.1800,mb,2014-12-03T00:06:47.328Z,"18km W of Lincoln, Montana",earthquake
nm60020625,2014-12-01 01:11:34.800,35.463100,-92.239300,1.000,1.80,md,10.0,100.799992,0.125764,0.2400,nm,2014-12-01T13:34:38.125Z,"14km SSE of Fairfield Bay, Arkansas",earthquake
mb14923536,2014-12-01 01:07:49.300,45.099100,-111.919600,6.100,1.30,mc,19.0,57.599995,0.159002,0.1200,mb,2014-12-03T00:06:41.997Z,"21km S of Virginia City, Montana",earthquake
ak11453419,2014-12-01 01:07:15.000,64.989600,-147.313200,0.000,1.40,ml,NaN,NaN,NaN,0.6900,ak,2014-12-09T02:04:47.492Z,"23km NNE of Badger, Alaska",earthquake
ak11453418,2014-12-01 01:05:01.000,63.461100,-148.765900,13.800,0.60,ml,NaN,NaN,NaN,0.5400,ak,2014-12-09T02:05:51.183Z,"12km NE of Cantwell, Alaska",earthquake
usc000t6y1,2014-12-01 01:04:17.890,7.142900,126.884400,176.670,4.30,mb,NaN,134.000000,1.297000,0.8700,us,2015-02-24T00:35:14.040Z,"37km ESE of Santiago, Philippines",earthquake
nc72358471,2014-12-01 01:03:50.530,38.764500,-122.890833,4.130,1.14,md,37.0,156.000000,0.035690,0.0500,nc,2014-12-10T21:02:04.714Z,"11km ESE of Cloverdale, California",earthquake
nc72358476,2014-12-01 01:02:27.710,37.473333,-118.786333,5.920,0.73,md,13.0,111.000000,0.121400,0.0300,nc,2014-12-03T17:30:04.727Z,"25km SE of Mammoth Lakes, California",earthquake
nc72358466,2014-12-01 01:00:29.200,38.767167,-122.888333,3.560,0.82,md,26.0,143.000000,0.033850,0.0600,nc,2014-12-11T06:55:03.683Z,"11km ESE of Cloverdale, California",earthquake
nc72358461,2014-12-01 00:59:41.910,38.830166,-122.833504,1.730,0.29,md,7.0,222.000000,0.008552,0.0100,nc,2014-12-01T01:33:06.454Z,"8km NW of The Geysers, California",earthquake
ci37065303,2014-12-01 00:58:43.430,34.536167,-116.525833,4.310,1.44,ml,20.0,65.000000,0.134700,0.1600,ci,2014-12-01T18:45:06.920Z,"40km ENE of Lucerne Valley, California",earthquake
ak11453417,2014-12-01 00:42:54.000,62.028000,-145.138900,15.900,1.20,ml,17.0,86.399993,NaN,0.6800,ak,2014-12-09T02:05:13.927Z,"23km ESE of Glennallen, Alaska",earthquake
ak11453416,2014-12-01 00:41:04.000,65.117800,-148.999600,12.500,0.60,ml,11.0,169.199986,NaN,0.7400,ak,2014-12-09T02:05:13.074Z,"55km WNW of Ester, Alaska",earthquake
usb000t1gp,2014-12-01 00:40:02.720,37.209600,71.945800,95.570,4.20,mb,NaN,125.000000,1.097000,0.9100,us,2015-02-24T00:35:14.040Z,"11km ESE of Roshtqal'a, Tajikistan",earthquake
ak11453414,2014-12-01 00:30:21.000,63.479600,-148.224300,0.800,0.80,ml,NaN,NaN,NaN,0.5100,ak,2014-12-09T02:04:34.872Z,"37km ENE of Cantwell, Alaska",earthquake
usc000t6yn,2014-12-01 00:24:33.140,-24.634000,-179.601800,470.860,4.50,mb,NaN,131.000000,10.547000,0.7400,us,2015-02-24T00:35:14.040Z,South of the Fiji Islands,earthquake
ak11453410,2014-12-01 00:16:26.000,65.160000,-149.016800,11.400,0.60,ml,NaN,NaN,NaN,0.7300,ak,2014-12-10T01:03:17.366Z,"58km NW of Ester, Alaska",earthquake
ak11453411,2014-12-01 00:16:21.000,62.795800,-150.387800,79.700,1.20,ml,NaN,NaN,NaN,0.4500,ak,2014-12-09T02:05:53.895Z,"54km NNW of Talkeetna, Alaska",earthquake
ak11453391,2014-12-01 00:10:16.000,60.963900,-146.762900,14.800,3.80,ml,NaN,NaN,NaN,0.6900,ak,2015-03-24T18:25:07.628Z,"29km SW of Valdez, Alaska",earthquake
ak11453395,2014-12-01 00:09:39.000,58.869100,-154.415900,108.400,2.40,ml,NaN,NaN,NaN,0.6700,ak,2014-12-10T01:04:25.209Z,"102km SSE of Old Iliamna, Alaska",earthquake
nc72358451,2014-12-01 00:09:25.350,38.843498,-122.825836,2.370,0.43,md,8.0,107.000000,0.008991,0.0300,nc,2014-12-01T01:15:02.814Z,"9km WNW of Cobb, California",earthquake
ak11453390,2014-12-01 00:05:54.000,65.152100,-148.992000,9.500,0.40,ml,NaN,NaN,NaN,0.6900,ak,2014-12-10T01:03:01.225Z,"57km NW of Ester, Alaska",earthquake
ak11453389,2014-12-01 00:04:05.000,60.227200,-147.024500,2.500,1.60,ml,NaN,NaN,NaN,0.7300,ak,2014-12-09T02:04:46.894Z,"78km WSW of Cordova, Alaska",earthquake

In [5]:
df.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms
count,120108.000000,120108.000000,120107.000000,120065.000000,59688.000000,94935.000000,85682.000000,119716.000000
mean,38.399579,-99.961402,28.375029,1.793958,17.878284,124.048978,0.893198,0.358174
std,21.938258,82.996858,62.215416,1.343466,14.911369,68.518595,2.903966,0.364046
min,-73.462000,-179.998900,-9.900000,-0.970000,0.000000,9.000000,0.000000,0.000000
25%,34.228917,-147.742025,4.100000,0.820000,8.000000,74.000000,0.020760,0.070000
50%,38.805300,-120.832000,9.200000,1.400000,14.000000,107.000000,0.073670,0.200000
75%,53.889500,-116.068100,22.880000,2.400000,22.000000,155.000000,0.447000,0.590000
max,86.651400,179.998000,697.360000,8.200000,365.000000,356.400000,64.498000,8.460000

In [6]:
df.sort_values(by='mag',ascending=False).head(20)

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,id,updated,place,type
37371,2014-04-01 23:46:47.260,-19.6097,-70.7691,25.00,8.2,mww,NaN,23.0,0.609,0.66,us,usc000nzvd,2015-07-30T16:24:51.223Z,"94km NW of Iquique, Chile",earthquake
50562,2014-06-23 20:53:09.700,51.8486,178.7352,109.00,7.9,mww,NaN,22.0,0.133,0.71,us,usc000rki5,2015-04-18T21:54:08.699Z,"19km SE of Little Sitkin Island, Alaska",earthquake
36918,2014-04-03 02:43:13.110,-20.5709,-70.4931,22.40,7.7,mww,NaN,44.0,1.029,0.82,us,usc000p27i,2015-06-06T07:31:05.755Z,"53km SW of Iquique, Chile",earthquake
33808,2014-04-12 20:14:39.300,-11.2701,162.1481,22.56,7.6,mww,NaN,13.0,2.828,0.71,us,usc000phx5,2015-04-18T21:54:27.398Z,"93km SSE of Kirakira, Solomon Islands",earthquake
31496,2014-04-19 13:28:00.810,-6.7547,155.0241,43.37,7.5,mww,NaN,16.0,3.820,1.25,us,usb000pr89,2015-04-18T21:54:18.633Z,"70km SW of Panguna, Papua New Guinea",earthquake
33537,2014-04-13 12:36:19.230,-11.4633,162.0511,39.00,7.4,mww,NaN,17.0,2.885,1.00,us,usc000piqj,2015-08-13T19:29:13.018Z,"112km S of Kirakira, Solomon Islands",earthquake
95913,2014-10-14 03:51:34.460,12.5262,-88.1225,40.00,7.3,mww,NaN,18.0,1.078,0.70,us,usb000slwn,2015-08-13T19:35:02.679Z,"74km S of Intipuca, El Salvador",earthquake
31850,2014-04-18 14:27:24.920,17.3970,-100.9723,24.00,7.2,mww,NaN,46.0,2.250,1.20,us,usb000pq41,2015-08-13T19:30:39.599Z,"33km ESE of Petatlan, Mexico",earthquake
34318,2014-04-11 07:07:23.130,-6.5858,155.0485,60.53,7.1,mww,NaN,21.0,3.729,0.88,us,usc000pft9,2014-07-01T02:37:56.000Z,"56km WSW of Panguna, Papua New Guinea",earthquake
106285,2014-11-15 02:31:41.720,1.8929,126.5217,45.00,7.1,mww,NaN,18.0,1.397,0.71,us,usc000sxh8,2015-03-20T18:42:02.735Z,"154km NW of Kota Ternate, Indonesia",earthquake
111052,2014-11-01 18:57:22.380,-19.6903,-177.7587,434.00,7.1,mww,NaN,13.0,4.415,0.84,us,usc000stdc,2015-01-20T09:03:09.040Z,"144km NE of Ndoi Island, Fiji",earthquake
97602,2014-10-09 02:14:31.440,-32.1082,-110.8112,16.54,7.0,mww,NaN,22.0,5.127,0.43,us,usb000sk6k,2015-08-13T19:31:44.129Z,Southern East Pacific Rise,earthquake
47934,2014-06-29 07:52:55.170,-55.4703,-28.3669,8.00,6.9,mww,NaN,25.0,4.838,0.76,us,usc000rngj,2014-09-26T11:49:45.000Z,"154km NNW of Visokoi Island,",earthquake
78063,2014-08-03 00:22:03.680,0.8295,146.1688,13.00,6.9,mww,NaN,12.0,6.393,0.93,us,usb000rzki,2014-10-29T19:52:55.000Z,Federated States of Micronesia region,earthquake
50609,2014-06-23 19:19:15.940,-29.9772,-177.7247,20.00,6.9,mww,NaN,35.0,0.751,0.99,us,usc000rkg5,2014-09-19T17:23:16.000Z,"80km SSE of Raoul Island, New Zealand",earthquake
14025,2014-02-12 09:19:49.060,35.9053,82.5864,10.00,6.9,mww,NaN,18.0,7.496,0.83,us,usc000mnvj,2015-01-30T23:03:45.902Z,"272km ESE of Hotan, China",earthquake
61294,2014-07-21 14:54:41.000,-19.8015,-178.4001,615.42,6.9,mww,NaN,15.0,3.934,0.96,us,usb000ruzk,2014-10-17T21:12:13.000Z,"99km NNE of Ndoi Island, Fiji",earthquake
37367,2014-04-01 23:57:58.790,-19.8927,-70.9455,28.42,6.9,mww,NaN,119.0,0.828,0.93,us,usc000nzwm,2014-05-29T23:32:13.000Z,"91km WNW of Iquique, Chile",earthquake
39915,2014-05-24 09:25:02.440,40.2893,25.3889,6.43,6.9,mww,NaN,25.0,0.402,0.67,us,usb000r2hc,2015-01-28T09:17:17.266Z,"22km SSW of Kamariotissa, Greece",earthquake
66278,2014-07-07 11:23:54.780,14.7240,-92.4614,53.00,6.9,mww,NaN,51.0,0.263,1.38,us,usc000rr6a,2015-01-28T13:08:13.282Z,"4km W of Puerto Madero, Mexico",earthquake

In [7]:
df.place

0                     26km S of Redoubt Volcano, Alaska
1                               32km S of Alamo, Nevada
2                      12km NNW of North Nenana, Alaska
3                            22km S of Cantwell, Alaska
4                          10km WNW of Progreso, Mexico
5                              3km N of Tijuana, Mexico
6                 11km N of Borrego Springs, California
7                         61km NNW of Talkeetna, Alaska
8                            48km NNE of Kodiak, Alaska
9                        3km E of Livermore, California
10                 115km ESE of Taron, Papua New Guinea
11                          71km SE of Whittier, Alaska
12                     0km N of The Geysers, California
13                 4km WSW of Mammoth Lakes, California
14                 120km N of Raoul Island, New Zealand
15                        6km SSW of Lilbourn, Missouri
16                            South of the Fiji Islands
17                       27km ESE of Julian, California
18                      52km S of Lone Pine, California
19                           23km NNE of Badger, Alaska
20                        1km NNW of Angwin, California
21          14km NW of Helena Valley Northwest, Montana
22                 24km N of Searles Valley, California
23                    6km NW of The Geysers, California
24        16km WNW of Road Town, British Virgin Islands
25                            104km W of Willow, Alaska
26                   72km E of Amatignak Island, Alaska
27                  7km NW of Big Bear City, California
28                12km N of Borrego Springs, California
29                      37km E of Cape Yakataga, Alaska
                              ...
120078                    13km WNW of Medford, Oklahoma
120079                9km NW of The Geysers, California
120080                    6km NW of Banning, California
120081               11km ESE of Cloverdale, California
120082                        5km SW of Volcano, Hawaii
120083                 21km ESE of Three Rivers, Oregon
120084               11km ESE of Cloverdale, California
120085                       18km W of Lincoln, Montana
120086              14km SSE of Fairfield Bay, Arkansas
120087                 21km S of Virginia City, Montana
120088                       23km NNE of Badger, Alaska
120089                      12km NE of Cantwell, Alaska
120090                37km ESE of Santiago, Philippines
120091               11km ESE of Cloverdale, California
120092             25km SE of Mammoth Lakes, California
120093               11km ESE of Cloverdale, California
120094                8km NW of The Geysers, California
120095           40km ENE of Lucerne Valley, California
120096                   23km ESE of Glennallen, Alaska
120097                        55km WNW of Ester, Alaska
120098               11km ESE of Roshtqal'a, Tajikistan
120099                     37km ENE of Cantwell, Alaska
120100                        South of the Fiji Islands
120101                         58km NW of Ester, Alaska
120102                    54km NNW of Talkeetna, Alaska
120103                        29km SW of Valdez, Alaska
120104                 102km SSE of Old Iliamna, Alaska
120105                      9km WNW of Cobb, California
120106                         57km NW of Ester, Alaska
120107                      78km WSW of Cordova, Alaska
Name: place, Length: 120108, dtype: object

In [64]:
a=df['place'].str.rsplit(',', expand=True, n=1)
b=["Alabama","Alaska","Arizona","Arkansas","California","Colorado",
  "Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois",
  "Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland",
  "Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana",
  "Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York",
  "North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
  "Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah",
  "Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]
a=set(a[1])
b=set(b)
l=[]
for i in a:
    if i not in b:
        l.append(i)
# print(l)

l=list(l)
# print(df2)
newdf=df.assign(country=l)
print(newdf)

ValueError: Length of values does not match length of index

In [8]:

a=[6,4,9,0,8]
b=[3,4,5,6]
l=[]
for i in a:
    if i not in b:
        l.append(i)
print(l)

[9, 0, 8]

ipl data set
mathches 
cbond for plotting